## =============================================================================
## Geant4 macro for modelling simplified sampling calorimeters
## =============================================================================
##
/control/verbose 0
/run/numberOfThreads 4
/run/verbose 0
##
## -----------------------------------------------------------------------------
## Setup the ATLASbar simplified sampling calorimeter:
##   = 50 Layers of:
##     - Absorber 1 (gap) : 2.3 mm Lead
##     - Absorber 2 (abs.): 5.7 mm liquid-Argon
## -----------------------------------------------------------------------------
/testem/det/setSizeYZ 40 cm
/testem/det/setNbOfLayers 50
/testem/det/setNbOfAbsor 2
/testem/det/setAbsor 1 G4_Pb 2.3 mm
/testem/det/setAbsor 2 G4_lAr 5.7 mm
## -----------------------------------------------------------------------------
## Optionally, set a constant magnetic filed:
##   = set a constant, 2 Tesla field perpendicular to the [1,0,0] beam direction
## -----------------------------------------------------------------------------
##/testem/det/setField 0 0 2.0 tesla
##
## -----------------------------------------------------------------------------
## Set the physics list (more exactly, the EM physics constructor e-/e+, gamma):
##
## NOTE: the full-fledged G4HepEm physics with its special tracking, i.e.
##   `HepEmTracking` below, is the recommended usage of G4HepEm through its
##   `G4HepEmTrackingManager`. This provides correct and complete physics
##    (i.e. including nuclear interactions as well if attached to the particles)
##    combined with maximal computing performance benefits, it requires at least
##    Geant4-11.0. The other option is `HepEm`, i.e. connecting only the G4HepEm
##    physics (through the `G4VProcess` interface), is incomplete (e.g. nuclear
##    interactions aren't incorporated properly) and not efficient as it doesn't
##    contain the special tracking component).
##
##  1. 'HepEmTracking' : full-fleged `G4HepEmTrackingManager`(G4HepEm physics with its special tracking)
##  2. 'G4Em'          : native G4 EM physics that corresponds to the G4HepEm physics
##  3. 'G4 EM-opt0'    : the native G4 EM standard opt0 physics constructor
##  4. 'HepEm'         : G4HepEm physics using the `G4VProcess` interface (only for )
##
## NOTE: nuclear interactions are also added to e-/e+ and gamma through the
##       `G4EmExtraPhysics` constructor (see the `PhysicsList`).
## -----------------------------------------------------------------------------
/testem/phys/addPhysics HepEmTracking
##/testem/phys/addPhysics G4Em
##/testem/phys/addPhysics emstandard_opt0
## NOTE: `HepEm` is only for development!
##/testem/phys/addPhysics HepEm
##
## -----------------------------------------------------------------------------
## Set the verbosity of the physics list (parameters, setting, configuration)
## -----------------------------------------------------------------------------
/testem/phys/verbose 1
##
## -----------------------------------------------------------------------------
## Use the gamma-general process in Geant4 (similarly to HepEmTracking)
## -----------------------------------------------------------------------------
/process/em/UseGeneralProcess true
##
## -----------------------------------------------------------------------------
## Option to apply cuts also beyond ionisation and bremsstrahlung
## -----------------------------------------------------------------------------
/process/em/applyCuts true
##
## -----------------------------------------------------------------------------
## Option to set the production cut value in the "Woodcock_Region" (calorimeter)
## -----------------------------------------------------------------------------
/testem/det/setWDCKRegionCut 0.7 mm
##
## -----------------------------------------------------------------------------
## Set secondary production threshold, init. the run and set primary properties
## -----------------------------------------------------------------------------
/run/setCut 0.7 mm
/run/initialize
/gun/particle e-
/gun/energy 10 GeV
##
## -----------------------------------------------------------------------------
## Run the simulation with the given number of events and print list of processes
## -----------------------------------------------------------------------------
##/tracking/verbose 1
/run/beamOn 1000
/process/list
